<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtID</name>
   <tag></tag>
   <elementGuidId>ecca1e09-97f1-4dc3-9bb0-41740e8e9c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>144cc5ce-3422-444f-a9e4-52fd23d4bb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtID</value>
      <webElementGuid>3eb7483f-2c0b-4404-9fe1-cd4b1af24740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21434ddc-3906-4ee3-85e9-4ab2cc131d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>9dfba804-1f5a-4180-a0b3-f04bc32979f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtID</value>
      <webElementGuid>ec7ec1a8-1ba2-4d22-b228-27338f6d6992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-43a35af71b25a1fd17b1508f553f3df9</value>
      <webElementGuid>f4ad0e0a-df2e-4814-8774-c3120a60a381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtID']</value>
      <webElementGuid>a3f6bf53-8f64-4769-ba38-c0e9adac0f8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtID']</value>
      <webElementGuid>230cc277-c1bc-4baf-8cc7-01a4536a488d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtID' and @type = 'text' and @id = 'txtID']</value>
      <webElementGuid>3f1c59ad-e9f2-4745-a7fb-6c20cd39c43f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
