<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Anggota_txtID</name>
   <tag></tag>
   <elementGuidId>5d0291ec-e3c4-4ee9-9fdf-fb5c4939506e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cbc8b95-e778-49e0-8886-22d7ee1bcaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtID</value>
      <webElementGuid>042b3b53-f01d-4851-913d-1e0e5372f2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f292f222-1e7e-4e7c-9ef5-9d07a659a167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>3eaf6e9c-d98d-4e86-b7e0-7f51b57b8959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtID</value>
      <webElementGuid>198a20a7-1ac0-47d6-9533-a65b48ea884d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtID&quot;)</value>
      <webElementGuid>cf54a4a2-18e8-46d6-9e4f-9c633e5bb4db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtID']</value>
      <webElementGuid>7be8c49c-fc81-41bc-b72c-dcfe94da7adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>01e5fa28-7a0e-455a-a400-3fbfe72c6ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtID' and @type = 'text' and @id = 'txtID']</value>
      <webElementGuid>bb864c39-4065-4b7c-880b-71382a85e2d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
